'''
Even Fibonacci Numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

sum = 0    
num1 = 0;   
num2 = 1;   
 
while num2 < 4e6:

    num1, num2 = num2, num1+num2
 
    if num1%2 == 0:
        sum += num1
 
print('The sum is: ' + str(sum))

# Ans = 4613732
# Not by myself